// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWhdrNaWwRYyIv05OQLMnzJjCJjwwWlw',
    appId: '1:155781668912:android:bb75699006722cdac88df5',
    messagingSenderId: '155781668912',
    projectId: 'noti-flutter-8a263',
    storageBucket: 'noti-flutter-8a263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm3-GRI2SFvk3OHuNlZePrLTQ-HljPeKE',
    appId: '1:155781668912:ios:a31cb1d2b1b68931c88df5',
    messagingSenderId: '155781668912',
    projectId: 'noti-flutter-8a263',
    storageBucket: 'noti-flutter-8a263.firebasestorage.app',
    iosBundleId: 'com.example.notiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm3-GRI2SFvk3OHuNlZePrLTQ-HljPeKE',
    appId: '1:155781668912:ios:a31cb1d2b1b68931c88df5',
    messagingSenderId: '155781668912',
    projectId: 'noti-flutter-8a263',
    storageBucket: 'noti-flutter-8a263.firebasestorage.app',
    iosBundleId: 'com.example.notiFlutter',
  );
}
